# Onboarding {#onboarding}

::: {.rmdnote data-latex="{note}"}

This chapter contains the short, practical essentials for onboarding. If you need more inspiration about data curation, or you would like to read more about our work, please referr to the subsequent chapters. 

:::

**You can become a curator by invitation to the project, or by applying in a short letter.**

**Your simplified resumé and profile picture.** Take a look at profile of any [Digital Music Observatory curators](https://music.dataobservatory.eu/#contributors) to see what we are aiming at. 

You can download the Curatorial template from [here](https://raw.githubusercontent.com/dataobservatory-eu/music/main/content/authors/curator/_index.md).

> Whatever is shown behind a # sign is a commentary to give you instructions how to  fill in the form. You can delete those lines or leave in place, they will not be shown.



## Must have items {-}

- [x] Your biography must be machine readable.  It consists of a `TOML` heading and `markdown` body.  Change our template with any text editor. The editor should preferably not Word, or should save to standard text files in 'UTF-8' coding--non-English version Windows computers use your national character set by default, but you can always chose UTF-8 encoding in `Save as`. Even if you are not familiar with these markups, by opening the template, it should be self explanatory. 
`name: New Curators` should be changed to `name: <Your Name>` 
- [x] You must send a profile picture that is at least 500px wide (jpg or png format.) It can be bigger, and preferrably not a very "narrow" cut, as all avatars will be behind a ciruclar mask (see [other curators](https://music.dataobservatory.eu/#contributors).)
- [ORCiD](https://orcid.org/) Your ORCiD ID, which will enable us to unambigously attribute your contributions. ORCiD is used in open science and other publishing to unambigously attribute copyrights and other intellectual property rights to a person. It takes a few minutes to register an account if you do not have it yet. We will attribute your name and ORCiD ID on all assets that you contribute to.
- [x] At least one of these accounts where other contributors, curators can find you: a link to your _LinkedIn_, professional _Twitter_, professional _Facebook_, or _Academia_ or _Google Scholar_ account. Because of its diverse use among business, NGO and academic professionals, we recommend that you give a LinkedIn link. 
- [ ] You must abide the [Contributor Covenant Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/) (but *need not send* us proof) of pledging to make participation in our community a harassment-free experience for everyone, regardless of age, body size, visible or invisible disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, caste, color, religion, or sexual identity and orientation. (See [translations](https://www.contributor-covenant.org/translations/) and the related [FAQ](https://www.contributor-covenant.org/faq/).)

## Preferred

If you need help, get in touch with us, our preferred way of communication is  [keybase](https://keybase.io/). Keybase is an open-source, privacy and security concerned alternative to Slack and similar chat-based collaboration tools. Our observatories and Listen Local have their Keybase channels where you can interact with other curators and developers.

For collaboration on articles, publications, analysis you must have a [Github account ID](https://docs.github.com/en/get-started/signing-up-for-github/signing-up-for-a-new-github-account) Our project management dashboard and the FAQ is on Github, and all our source files will be versioned on Github. Github is the most popular open collaboration platform for open source software editors. If you do not write code, you will not contribute to our source files, but with a Github id you ask questions, take on tasks and report them ready on our project dashboard.

We have shared bibliographies on the open source, free [Zotero](https://www.zotero.org/) research assistant and we have a closed biblliography repository with BibLatex files on Github for the material that refer to in open science, open policy analysis, data science, and each other's work. The best place to share readings, bibliographies is *Zotero*, for preparing publications the Github accouunt. 


## Domain specific issues

### Creative industries
In some of our music related projects, we need to use Spotify, YouTube, Instagram accounts because they are used professionally. We can link these accounts to your profile if you use them in a professional capacity.
- [Spotify Account Link](https://open.spotify.com/user/rx4xjay1368opqg2i7nabuo5c): You must have a free or premium account on Spotify. We will ask playlists initially on Spotify for ease of collaboration. If you do not use Spotify, you can create a free account for your Listen Local contributions.

### Academia 
We use [ORCiD](https://orcid.org/) because we rely on Zenodo as an open source repository, but we can include almost any academic badge on your profile that you like, just make sure that you have an ORCiD ID, too. 


**Links and Identifiers** You can optionally attach to your profile your LinkedIn profile, Instagram, Facebook, Twitter, YouTube channel, Spotify Creator account, or anything that you use as a music professional---select at least one where artists can get in touch with you. 
Furtherore, for contributions to this project, we will need the following three identifiers from you:






